language: scala

sudo: false
  
scala:
- 2.12.7

jdk:
- oraclejdk8

notifications:
  email:
    recipients:
    - vlad@uralian.com

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
